on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo building code
      
  promote:
    runs-on: ubuntu-latest
    needs: [ build ]
    environment: prod
    steps:
      - run: echo promote
      
